version: '3.4'

services:
  db:
    container_name: 'mariadb-10'
    image: mariadb:10.4.12
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${PASSWORD}'
      TZ: 'Asia/Seoul'
    ports:
      - 3306:3306
    volumes:
      - db-config:/etc/mysql:ro
      - db-data:/var/lib/mysql/data
      
volumes:
  db-config:
  db-data: