version: "3.7"

services:

  file:
    container_name: 'samba'
    image: dperson/samba:aarch64
    restart: always
    environment:
      TZ: 'Asia/Seoul'
    ports:
      - 139:139
      - 40445:445
    volumes:
      - media-data:/mount

  torrent:
    container_name: 'rtorrent'
    image: mondedie/rutorrent:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      UID: 1000
      GID: 1000
      HTTP_AUTH: 'true'
      PORT_RTORRENT: 46000
    # networks:
    #   - overlay
    ports:
      - 8080:8080
      - 46000:46000
    volumes:
      - media-config:/config
      - media-data:/data

  dlna:
    container_name: 'minidlna'
    image: vladgh/minidlna:latest
    restart: always
    environment:
      TZ: 'Asia/Seoul'
      MINIDLNA_MEDIA_DIR: '/media'
      MINIDLNA_FRIENDLY_NAME: 'MiniDLNA'
    # networks:
    #   - overlay
    ports:
      - 8200:8200
      - 1900:1900/udp
    volumes:
      - media-data:/media

volumes:
  media-data:
  media-config:

# networks:
#   overlay:
